######################## default configuration ####################
baseURL = "https://nervous-thompson-9d00a1.netlify.com/"
title = "unf-montreal.ca"
theme = "educenter"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "educenter" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################## navigation ###############################

# main menu
[[Languages.fr.menu.main]]
name = 'À propos de nous'
URL = 'about'
weight = 1
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "À propos de nous"
  name = "Historique"
  URL = "historic"
  weight = 1


  [[Languages.fr.menu.main]]
  parent = "À propos de nous"
  name = "Équipe"
  URL = "team"
  weight = 2

  [[Languages.fr.menu.main]]
  parent = "À propos de nous"
  name = "About"
  URL = "about"
  weight = 3

  [[Languages.fr.menu.main]]
  name = "Nouvelles"
  URL = "News"
  weight = 2

  [[Languages.fr.menu.main]]
  weight = 3
  name = "Votre étude"
  hasChildren = true

    [[Languages.fr.menu.main]]
    parent = "Votre étude"
    name = "Formulaires à télécharger"
    URL = "forms"
    weight = 1

    [[Languages.fr.menu.main]]
    parent = "Votre étude"
    name = "Évaluation des projets"
    URL = "project_evaluation"
    weight = 2

    [[Languages.fr.menu.main]]
    parent = "Votre étude"
    name = "Guide de soumission des projets"
    URL = "project_submission"
    weight = 3

    [[Languages.fr.menu.main]]
    parent = "Votre étude"
    name = "Dates butoirs pour la soumission des projets de recherche"
    URL = "project_submission_deadlines"
    weight = 4

    [[Languages.fr.menu.main]]
    parent = "Votre étude"
    name = "Taux horaires et politique de facturation"
    URL = "rates"
    weight = 5

    [[Languages.fr.menu.main]]
    parent = "Votre étude"
    name = "Suivi des projets"
    URL = "project_followup"
    weight = 6

  [[Languages.fr.menu.main]]
  name = "Recherche"
  URL = "research"
  weight = 4

    [[Languages.fr.menu.main]]
    parent = "Recherche"
    name = "Sécurité"
    URL = "research_safety_guidelines"
    weight = 1

    [[Languages.fr.menu.main]]
    parent = "Recherche"
    name = "Infrastructure"
    URL = "research_infrastructure"
    weight = 2

    [[Languages.fr.menu.main]]
    parent = "Recherche"
    name = "Liste des publications"
    URL = "research_published_papers"
    weight = 3

    [[Languages.fr.menu.main]]
    parent = "Recherche"
    name = "Découverte fortuite"
    URL = "research_coincidental_findings"
    weight = 4

  [[Languages.fr.menu.main]]
  name = "Services"
  URL = "services"
  weight = 5

    [[Languages.fr.menu.main]]
    parent = "Services"
    name = "Reservation IRM"
    URL = "service_reserve_mri"
    weight = 1

    [[Languages.fr.menu.main]]
    parent = "Services"
    name = "Reservation Salle de Simulation"
    URL = "service_reserve_simulation_room"
    weight = 2

    [[Languages.fr.menu.main]]
    parent = "Services"
    name = "Récupération des données IRM"
    URL = "service_mri_data_download"
    weight = 3

    [[Languages.fr.menu.main]]
    parent = "Services"
    name = "Traitement des données IRM"
    URL = "service_mri_data_processing"
    weight = 4

    [[Languages.fr.menu.main]]
    parent = "Services"
    name = "Images et Logos"
    URL = "service_images_logos"
    weight = 5

    # [[Languages.fr.menu.main]]
    # parent = "Services"
    # name = "Documentation"
    # URL = "service_documentation"
    # weight = 6

  [[Languages.fr.menu.main]]
  name = "Contact"
  URL = "Contact"
  weight = 6

[[menu.main]]
name = "About"
URL = "about"
weight = 1
hasChildren = true

  [[menu.main]]
  parent = "About"
  name = "UNF Historic"
  URL = "historic"
  weight = 1

  [[menu.main]]
  parent = "About"
  name = "Team"
  URL = "team"
  weight = 2

[[menu.main]]
name = "News"
URL = "News"
weight = 2

[[menu.main]]
weight = 3
name = "Your study"
hasChildren = true

  [[menu.main]]
  parent = "Your study"
  name = "Forms and documents"
  URL = "forms"
  weight = 1

  [[menu.main]]
  parent = "Your study"
  name = "Project Evaluation"
  URL = "project_evaluation"
  weight = 2

  [[menu.main]]
  parent = "Your study"
  name = "Project Submission"
  URL = "project_submission"
  weight = 3

  [[menu.main]]
  parent = "Your study"
  name = "Project Submission Deadlines"
  URL = "project_submission_deadlines"
  weight = 4

  [[menu.main]]
  parent = "Your study"
  name = "Hourly Rates"
  URL = "rates"
  weight = 5

  [[menu.main]]
  parent = "Your study"
  name = "Project Follow-up"
  URL = "project_followup"
  weight = 6

[[menu.main]]
name = "Research"
URL = "research"
weight = 4

  [[menu.main]]
  parent = "Research"
  name = "Safety Guidelines"
  URL = "research_safety_guidelines"
  weight = 1

  [[menu.main]]
  parent = "Research"
  name = "Infrastructure"
  URL = "research_infrastructure"
  weight = 2

  [[menu.main]]
  parent = "Research"
  name = "Published Papers"
  URL = "research_published_papers"
  weight = 3

  [[menu.main]]
  parent = "Research"
  name = "Coincidental Findings"
  URL = "research_coincidental_findings"
  weight = 4

[[menu.main]]
name = "Service"
URL = "Service"
weight = 5

  [[menu.main]]
  parent = "Service"
  name = "Reserve MRI"
  URL = "service_reserve_mri"
  weight = 1

  [[menu.main]]
  parent = "Service"
  name = "Reserve Simulation Room"
  URL = "service_reserve_simulation_room"
  weight = 2

  [[menu.main]]
  parent = "Service"
  name = "MRI Data Download"
  URL = "service_mri_data_download"
  weight = 3

  [[menu.main]]
  parent = "Service"
  name = "MRI Data Processing"
  URL = "service_mri_data_processing"
  weight = 4

  [[menu.main]]
  parent = "Service"
  name = "Images & Logos"
  URL = "service_images_logos"
  weight = 5

  # [[menu.main]]
  # parent = "Service"
  # name = "Documentation"
  # URL = "service_documentation"
  # weight = 6

[[menu.main]]
name = "Contact"
URL = "Contact"
weight = 6

# footer menu

[[menu.footer]]
name = "teacher"
URL = "teacher"

[[menu.footer]]
name = "notice"
URL = "notice"

[[menu.footer]]
name = "event"
URL = "event"

[[menu.footer]]
name = "scholarship"
URL = "scholarship"

[[menu.footer]]
name = "research"
URL = "research"

enableGitInfo = true

#################### default parameters ################################
[params]
logo = "images/logo_unf.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact info
address = "4565 Queen Mary Rd, Montreal, QC H3W 1W5"
mobile = "514-340-3540 ext. 3633"
email = "support.unf@criugm.qc.ca"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true


##################### DOCSY #####################
# Everything below this are Site Params

time_format_default = "02.01.2006"
time_format_blog = "02.01.2006"
copyright = "The Docsy Authors"
privacy_policy = "https://policies.google.com/privacy"

# First one is picked as the Twitter card image if not set on page.
# images = ["images/project-illustration.png"]

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Releases"

# Flag used in the "version-banner" partial to decide whether to display a 
# banner on every page indicating that this is an archived version of the docs.
# Set this flag to "true" if you want to display the banner.
archived_version = false

# The version number for the version of the docs represented in this doc set.
# Used in the "version-banner" partial to display a version number for the 
# current doc set.
version = "0.0"

# A link to latest version of the docs. Used in the "version-banner" partial to
# point people to the main doc site.
url_latest_version = "https://example.com"

# Repository configuration (URLs for in-page links to opening issues and suggesting changes)
github_repo = "https://github.com/unf-montreal.ca/docsy-example"
# An optional link to a related project repo. For example, the sibling repository where your product code lives.
github_project_repo = "https://github.com/unf-montreal/unf-montreal.ca"

# Specify a value here if your content directory is not in your repo's root directory
# github_subdir = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
#  Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
#  Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = true

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
	name = "User mailing list"
	url = "https://example.org/mail"
	icon = "fa fa-envelope"
        desc = "Discussion and help from your fellow users"
[[params.links.user]]
	name ="Twitter"
	url = "https://example.org/twitter"
	icon = "fab fa-twitter"
        desc = "Follow us on Twitter to get the latest news!"
[[params.links.user]]
	name = "Stack Overflow"
	url = "https://example.org/stack"
	icon = "fab fa-stack-overflow"
        desc = "Practical questions and curated answers"
# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/google/docsy"
	icon = "fab fa-github"
        desc = "Development takes place here!"
[[params.links.developer]]
	name = "Slack"
	url = "https://example.org/slack"
	icon = "fab fa-slack"
        desc = "Chat with other project developers"
[[params.links.developer]]
	name = "Developer mailing list"
	url = "https://example.org/mail"
	icon = "fa fa-envelope"
        desc = "Discuss development issues around the project"


[[params.versions]]
  version = "v0.3"
  url = "https://v0-3.kubeflow.org"

######################################################## END DOCSY ###########################################################


# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://goo.gl/maps/1ZXgXqEoeuQTfeMP9"
map_latitude = "45.491178"
map_longitude = "-73.623335"
map_marker = "images/marker.png"

############################# social site ########################
# [[params.social]]
# title = "facebook"
# icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
# link = "#"

[[params.social]]
title = "twitter"
icon = "fab fa-twitter" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/UNF_montreal"

[[params.social]]
title = "slack"
icon = "fab fa-slack" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "github"
icon = "fab fa-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/unfmontreal/"

# [[params.social]]
# title = "linkedin"
# icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
# link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/en"
weight = 1
home = "Home"
about= "About"
# copyright
copyright = "Copyright &copy; 2020 UNF"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/fr"
weight = 2
home = "Accueil"
about= "À propos de nous"
# copyright
copyright = "Copyright &copy; 2020 UNF"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true