######################## default configuration ####################
baseURL = "https://nervous-thompson-9d00a1.netlify.com/"
title = "unf-montreal.ca"
theme = "educenter"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "educenter" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
link = "plugins/filterizr/jquery.filterizr.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################## navigation ###############################

# main menu
[[Languages.fr.menu.main]]
name = 'À propos de nous'
URL = 'about'
weight = 1
hasChildren = true

  [[Languages.fr.menu.main]]
  parent = "À propos de nous"
  name = "Historique"
  URL = "historic"
  weight = 1


  [[Languages.fr.menu.main]]
  parent = "À propos de nous"
  name = "Équipe"
  URL = "team"
  weight = 2

  [[Languages.fr.menu.main]]
  name = "Nouvelles"
  URL = "News"
  weight = 2

  [[Languages.fr.menu.main]]
  weight = 3
  name = "Votre étude"
  hasChildren = true

    [[Languages.fr.menu.main]]
    parent = "Votre étude"
    name = "Formulaires à télécharger"
    URL = "forms"
    weight = 1

    [[Languages.fr.menu.main]]
    parent = "Votre étude"
    name = "Évaluation des projets"
    URL = "project_evaluation"
    weight = 2

    [[Languages.fr.menu.main]]
    parent = "Votre étude"
    name = "Guide de soumission des projets"
    URL = "project_submission"
    weight = 3

    [[Languages.fr.menu.main]]
    parent = "Votre étude"
    name = "Dates butoirs pour la soumission des projets de recherche"
    URL = "project_submission_deadlines"
    weight = 4

    [[Languages.fr.menu.main]]
    parent = "Votre étude"
    name = "Taux horaires et politique de facturation"
    URL = "rates"
    weight = 5

    [[Languages.fr.menu.main]]
    parent = "Votre étude"
    name = "Suivi des projets"
    URL = "project_followup"
    weight = 6

  [[Languages.fr.menu.main]]
  name = "Recherche"
  URL = "research"
  weight = 4

    [[Languages.fr.menu.main]]
    parent = "Recherche"
    name = "Sécurité"
    URL = "research_safety_guidelines"
    weight = 1

    [[Languages.fr.menu.main]]
    parent = "Recherche"
    name = "Infrastructure"
    URL = "research_infrastructure"
    weight = 2

    [[Languages.fr.menu.main]]
    parent = "Recherche"
    name = "Liste des publications"
    URL = "research_published_papers"
    weight = 3

    [[Languages.fr.menu.main]]
    parent = "Recherche"
    name = "Découverte fortuite"
    URL = "research_coincidental_findings"
    weight = 4

  [[Languages.fr.menu.main]]
  name = "Services"
  URL = "services"
  weight = 5

    [[Languages.fr.menu.main]]
    parent = "Services"
    name = "Reservation IRM"
    URL = "service_reserve_mri"
    weight = 1

    [[Languages.fr.menu.main]]
    parent = "Services"
    name = "Reservation Salle de Simulation"
    URL = "service_reserve_simulation_room"
    weight = 2

    [[Languages.fr.menu.main]]
    parent = "Services"
    name = "Récupération des données IRM"
    URL = "service_mri_data_download"
    weight = 3

    [[Languages.fr.menu.main]]
    parent = "Services"
    name = "Traitement des données IRM"
    URL = "service_mri_data_processing"
    weight = 4

    [[Languages.fr.menu.main]]
    parent = "Services"
    name = "Images et Logos"
    URL = "service_images_logos"
    weight = 5

    # [[Languages.fr.menu.main]]
    # parent = "Services"
    # name = "Documentation"
    # URL = "service_documentation"
    # weight = 6

  [[Languages.fr.menu.main]]
  name = "Contact"
  URL = "Contact"
  weight = 6

[[menu.main]]
name = "About"
URL = "about"
weight = 1
hasChildren = true

  [[menu.main]]
  parent = "About"
  name = "UNF Historic"
  URL = "historic"
  weight = 1

  [[menu.main]]
  parent = "About"
  name = "Team"
  URL = "team"
  weight = 2

[[menu.main]]
name = "News"
URL = "News"
weight = 2

[[menu.main]]
weight = 3
name = "Your study"
hasChildren = true

  [[menu.main]]
  parent = "Your study"
  name = "Forms and documents"
  URL = "forms"
  weight = 1

  [[menu.main]]
  parent = "Your study"
  name = "Project Evaluation"
  URL = "project_evaluation"
  weight = 2

  [[menu.main]]
  parent = "Your study"
  name = "Project Submission"
  URL = "project_submission"
  weight = 3

  [[menu.main]]
  parent = "Your study"
  name = "Project Submission Deadlines"
  URL = "project_submission_deadlines"
  weight = 4

  [[menu.main]]
  parent = "Your study"
  name = "Hourly Rates"
  URL = "rates"
  weight = 5

  [[menu.main]]
  parent = "Your study"
  name = "Project Follow-up"
  URL = "project_followup"
  weight = 6

[[menu.main]]
name = "Research"
URL = "research"
weight = 4

  [[menu.main]]
  parent = "Research"
  name = "Safety Guidelines"
  URL = "research_safety_guidelines"
  weight = 1

  [[menu.main]]
  parent = "Research"
  name = "Infrastructure"
  URL = "research_infrastructure"
  weight = 2

  [[menu.main]]
  parent = "Research"
  name = "Published Papers"
  URL = "research_published_papers"
  weight = 3

  [[menu.main]]
  parent = "Research"
  name = "Coincidental Findings"
  URL = "research_coincidental_findings"
  weight = 4

[[menu.main]]
name = "Service"
URL = "Service"
weight = 5

  [[menu.main]]
  parent = "Service"
  name = "Reserve MRI"
  URL = "service_reserve_mri"
  weight = 1

  [[menu.main]]
  parent = "Service"
  name = "Reserve Simulation Room"
  URL = "service_reserve_simulation_room"
  weight = 2

  [[menu.main]]
  parent = "Service"
  name = "MRI Data Download"
  URL = "service_mri_data_download"
  weight = 3

  [[menu.main]]
  parent = "Service"
  name = "MRI Data Processing"
  URL = "service_mri_data_processing"
  weight = 4

  [[menu.main]]
  parent = "Service"
  name = "Images & Logos"
  URL = "service_images_logos"
  weight = 5

  # [[menu.main]]
  # parent = "Service"
  # name = "Documentation"
  # URL = "service_documentation"
  # weight = 6

[[menu.main]]
name = "Contact"
URL = "Contact"
weight = 6

# footer menu

[[menu.footer]]
name = "teacher"
URL = "teacher"

[[menu.footer]]
name = "notice"
URL = "notice"

[[menu.footer]]
name = "event"
URL = "event"

[[menu.footer]]
name = "scholarship"
URL = "scholarship"

[[menu.footer]]
name = "research"
URL = "research"


#################### default parameters ################################
[params]
logo = "images/logo_unf.png"
# Meta data
description = "This is meta description"
author = "Themefisher"
# contact info
address = "4565 Queen Mary Rd, Montreal, QC H3W 1W5"
mobile = "514-340-3540 ext. 3633"
email = "support.unf@criugm.qc.ca"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = true

time_format_default = "02.01.2006"
sidebar_search_disable = false
# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

# Subscription
[params.subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://goo.gl/maps/1ZXgXqEoeuQTfeMP9"
map_latitude = "45.491178"
map_longitude = "-73.623335"
map_marker = "images/marker.png"

############################# social site ########################
# [[params.social]]
# title = "facebook"
# icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
# link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/UNF_montreal"

# [[params.social]]
# title = "instagram"
# icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
# link = "#"

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/unfmontreal/"

# [[params.social]]
# title = "linkedin"
# icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
# link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
about= "About"
# copyright
copyright = "Copyright &copy; 2020 UNF"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
about= "À propos de nous"
# copyright
copyright = "Copyright &copy; 2020 UNF"
