# Hugo build configuration for Netlify 
# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

# Default build settings
[build]
  publish = "public"
  command = "npm install postcss-cli && hugo"

# "production" environment specific build settings
[build.environment]
  HUGO_VERSION = "0.62.2"
  HUGO_THEME = "educenter"
